name: movielistwithredux
description: The movie list from course 5 implemented with separation of bussiness and redux design
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:

  cupertino_icons: ^1.0.4

  flutter:
    sdk: flutter
  flutter_redux: ^0.9.0
  http: ^0.13.4
  meta: ^1.7.0
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0